const stateData = {
    "Andhra Pradesh": { image: "map/AndhraPradesh.jpg", livesImpacted: "800k+" },
    "Arunachal Pradesh": { image: "map/ArunachalPradesh.jpg", livesImpacted: "50k+" },
    "Assam": { image: "map/Assam.jpg", livesImpacted: "200k+" },
    "Bihar": { image: "map/Bihar.jpg", livesImpacted: "1M+" },
    "Chhattisgarh": { image: "map/Chhattisgarh.jpg", livesImpacted: "300k+" },
    "Goa": { image: "map/Goa.jpg", livesImpacted: "20k+" },
    "Gujarat": { image: "map/Gujarat.jpg", livesImpacted: "600k+" },
    "Haryana": { image: "map/Haryana.jpg", livesImpacted: "400k+" },
    "Himachal Pradesh": { image: "map/Himachal Pradesh.jpg", livesImpacted: "150k+" },
    "Jharkhand": { image: "map/Jharkhand.jpg", livesImpacted: "500k+" },
    "Karnataka": { image: "map/Karnataka.jpg", livesImpacted: "750k+" },
    "Kerala": { image: "map/Kerala.jpg", livesImpacted: "300k+" },
    "Madhya Pradesh": { image: "map/Madhya Pradesh.jpg", livesImpacted: "1.2M+" },
    "Maharashtra": { image: "map/Maharashtra.jpg", livesImpacted: "2M+" },
    "Manipur": { image: "map/Manipur.jpg", livesImpacted: "40k+" },
    "Meghalaya": { image: "map/Meghalaya.jpg", livesImpacted: "60k+" },
    "Mizoram": { image: "map/Mizoram.jpg", livesImpacted: "30k+" },
    "Nagaland": { image: "map/Nagaland.jpg", livesImpacted: "45k+" },
    "Odisha": { image: "map/Odisha.jpg", livesImpacted: "900k+" },
    "Punjab": { image: "map/Punjab.jpg", livesImpacted: "400k+" },
    "Rajasthan": { image: "map/Rajasthan.jpg", livesImpacted: "1.1M+" },
    "Sikkim": { image: "map/Sikkim.jpg", livesImpacted: "25k+" },
    "Tamil Nadu": { image: "map/TamilNadu.jpg", livesImpacted: "850k+" },
    "Telangana": { image: "map/Telangana.jpg", livesImpacted: "600k+" },
    "Tripura": { image: "map/Tripura.jpg", livesImpacted: "70k+" },
    "Uttar Pradesh": { image: "map/Uttar Pradesh.jpg", livesImpacted: "2.5M+" },
    "Uttarakhand": { image: "map/Uttarakhand.jpg", livesImpacted: "200k+" },
    "West Bengal": { image: "map/WestBengal.jpg", livesImpacted: "1.3M+" },
    "Jammu and Kashmir": { image: "map/Jammu and Kashmir.png", livesImpacted: "100k+" },
};